name: Check DataLayer Events on Homepages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-datalayer-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run DataLayer event checks
        run: npm run test:datalayer

      - name: Add summary
        run: cat report_datalayer_homepages.md >> $GITHUB_STEP_SUMMARY

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-datalayer-homepages
          path: |
            report_datalayer_homepages.json
            report_datalayer_homepages.md
